variable subnetgroup {}
variable allocated_storage {}
variable engine {}           
variable engine_version {}        
variable instance_class {}      
variable multi_az {}             
variable name {}             
variable username {}  
variable password {}                
variable port {}                
variable publicly_accessible {}
variable storage_encrypted {}  
variable storage_type {} 
variable cidr_block_private_subnet1 {}    
variable cidr_block_private_subnet2 {}
variable vpc_security_group_ids {}
variable vpc_id {}
variable prefix {}
variable "region" {}
variable "ssh_key_path" {}
variable "key_name" {}
variable "rds_port" {}
variable "cidr_block_public_subnet" {}
variable "instance_tenancy" {}
variable "instance_type" {}
variable "cidr_block_vpc" {}
variable "security_group_ec2" {}
variable "ami" {}
variable "security_group_db" {}
variable "cidr_block_route" {}
variable "public_subnet" {}
variable "subnet_id" {}
variable "subnet" {}